- name: ansible-playbook-sample
  hosts: localhost
  tasks:
    - name: Create a VPC with dedicated tenancy and a couple of tags
      amazon.aws.ec2_vpc_net:
        name: Module_dev2
        cidr_block: 10.10.0.20/16
        region: ap-northeast-1
        tags:
          module: ec2_vpc_net
        tenancy: default
    - name: Create a new subnet using net-id
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.10.1.76/24
        region: ap-northeast-1
        tags:
          module: ec2_vpc_subnet
    - name: Create a new subnet using net-name
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.10.2.32/24
        region: ap-northeast-1
        tags:
          module: ec2_vpc_subnet
    - name: Create a new Internet Gateway attached to the VPC
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: ap-northeast-1
        tags:
          Name: Module dev2 gateway
        state: present
      register:IGW
    - name: Create a new NAT Gateway attached to the VPC
      amazon.aws.ec2_vpc_nat_gateway:
        state: present
        subnet_id: "{{ public_subnet.subnet.id }}"
        region: ap-northeast-1
        if_exist_do_not_create: true
        wait: true
      register: NAT
    - name: Create a new route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: ap-northeast-1
        tags:
          Name: Module dev2 public route table
        subnets:
        - "{{ public_subnet.subnet.id }}"
        routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ IGW.gateway_id }}"
        state: present
      register: public_route_table
    - name: Create a new route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: ap-northeast-1
        tags:
          Name: Module dev2 private route table
        subnets:
        - "{{ private_subnet.subnet.id }}"
        routes:
        - dest: 0.0.0.0/0
          nat_gateway_id: "{{ NAT.nat_gateway_id }}"
        state: present
      register: private_route_table
