---
- name: Manage ec2 instance
  hosts: localhost
  collections:
    - amazon.aws
  vars:
    region:  us-east-2
    instance_name: rhel10-demo
    state: stopped #stopped or running or terminated
 
  tasks:
    - name: manage ec2 instance
      amazon.aws.ec2:
        region: "{{ region }}"
        instance_ids: "{{ lookup('amazon.aws.ec2_instance_info', filters={'tag:Name': instance_name, 'instance-state-name': 'running'}, region=region).instances | map(attribute='instance_id') | list }}"
        wait: true
        wait_timeout: 600
        state: "{{ state }}"
