---
- name: Manage ec2 instance
  hosts: localhost
  collections:
    - amazon.aws
  vars:
    region:  us-east-2
    instance_name: rhel10-demo
    state: stopped #stopped or running or terminated
 
  tasks:
    - name: Show the current state of the instance
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ instance_name }}"
      register: ec2_info
    - name: manage ec2 instance
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        instance_ids: "{{ ec2_info.instances[0].instance_id }}"
        wait: true
        wait_timeout: 600
        state: "{{ state }}"
      register: ec2_result
