[webservers]
web01.example.com ansible_host=10.20.129.182


# データベースサーバーグループ
[dbservers]
db01.example.com  ansible_host=10.20.13.111

# アプリケーションサーバーグループ
[appservers]
app01.example.com ansible_host=10.20.13.112
