---
- name: Install or uninstall packages
  hosts: all
  become: true
  gather_facts: false
  vars:
    packages_to_install: "{{ target_package | default('bash') }}"
    state: "{{ package_state | default('present') }}"  # 'present' or 'absent'

  tasks:  
    - name: Install package
      ansible.builtin.yum:
        name: "{{ packages_to_install }}"
        state: "{{ state }}"
      register: package_result
    - name: Display package installation result
      ansible.builtin.debug:
        msg: >-
          {% if package_result.changed %}
          Package '{{ packages_to_install }}' has been {{ state }}.
          {% else %}
          Package '{{ packages_to_install }}' was already {{ state }}.
          {% endif %}
